- name: Télécharger l'application depuis Artifactory
  ansible.builtin.get_url:
    url: "{{ artifactory_url }}/{{ artifactory_repo_path }}/{{ version }}/{{ artifactory_filename }}"
    dest: "/tmp/{{ artifactory_filename }}"
    url_username: "{{ artifactory_user }}"
    url_password: "{{ artifactory_password }}"
    force: yes
    validate_certs: no