- name: Télécharger l'application depuis Artifactory
  ansible.builtin.get_url:
    url: "{{ package_manager_url }}/{{ artefact_repo_path }}/{{ version }}/{{ artefact_filename }}"
    dest: "/tmp/{{ artefact_filename }}"
    headers:
      Authorization: "Bearer {{ lookup('env', 'GITHUB_TOKEN') }}"
    force: yes
    validate_certs: no